/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JDesktopPane;

/**
 *
 * @author Cravid Ekuikui
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Area_de_trabalho = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        Barra_de_menu = new javax.swing.JMenuBar();
        Menu_sistema = new javax.swing.JMenu();
        sub_menu_logout = new javax.swing.JMenuItem();
        Menu_tabelas = new javax.swing.JMenu();
        Tabela_user = new javax.swing.JMenu();
        Sub_menu_criar_user = new javax.swing.JMenuItem();
        Sub_menu_consultar_user = new javax.swing.JMenuItem();
        Tabela_clientes = new javax.swing.JMenu();
        Sub_menu_criar_cliente = new javax.swing.JMenuItem();
        Sub_menu_consultar_cliente = new javax.swing.JMenuItem();
        Tabela_tarefas = new javax.swing.JMenu();
        Sub_menu_criar_tarefa = new javax.swing.JMenuItem();
        Sub_menu_consultar_tarefas = new javax.swing.JMenuItem();
        Menu_tarefas = new javax.swing.JMenu();
        Sub_menu_atribuir_tarefa = new javax.swing.JMenuItem();
        Sub_menu_concluir_tarefa = new javax.swing.JMenuItem();
        Menu_relatorios = new javax.swing.JMenu();
        Sub_menu_relatorio_tarefas = new javax.swing.JMenuItem();
        Menu_sobre = new javax.swing.JMenu();
        Sub_menu_ajuda = new javax.swing.JMenuItem();
        Sub_menu_acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTTEC");

        Area_de_trabalho.setBackground(new java.awt.Color(0, 204, 204));
        Area_de_trabalho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Area_de_trabalho.setName("Area_de_Trabalho"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cravid4.png"))); // NOI18N

        Area_de_trabalho.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Area_de_trabalhoLayout = new javax.swing.GroupLayout(Area_de_trabalho);
        Area_de_trabalho.setLayout(Area_de_trabalhoLayout);
        Area_de_trabalhoLayout.setHorizontalGroup(
            Area_de_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Area_de_trabalhoLayout.createSequentialGroup()
                .addContainerGap(578, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Area_de_trabalhoLayout.setVerticalGroup(
            Area_de_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Area_de_trabalhoLayout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Barra_de_menu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        Menu_sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/page.png"))); // NOI18N
        Menu_sistema.setText("Sistema");
        Menu_sistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub_menu_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_out.png"))); // NOI18N
        sub_menu_logout.setText("Logout");
        sub_menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_logoutActionPerformed(evt);
            }
        });
        Menu_sistema.add(sub_menu_logout);

        Barra_de_menu.add(Menu_sistema);

        Menu_tabelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.png"))); // NOI18N
        Menu_tabelas.setText("Tabelas");
        Menu_tabelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Tabela_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        Tabela_user.setText("Usuários");

        Sub_menu_criar_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        Sub_menu_criar_user.setText("Criar Usuário");
        Sub_menu_criar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_criar_userActionPerformed(evt);
            }
        });
        Tabela_user.add(Sub_menu_criar_user);

        Sub_menu_consultar_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_edit.png"))); // NOI18N
        Sub_menu_consultar_user.setText("Consultar Usuários");
        Sub_menu_consultar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_consultar_userActionPerformed(evt);
            }
        });
        Tabela_user.add(Sub_menu_consultar_user);

        Menu_tabelas.add(Tabela_user);

        Tabela_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        Tabela_clientes.setText("Clientes");

        Sub_menu_criar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_add.png"))); // NOI18N
        Sub_menu_criar_cliente.setText("Criar Cliente");
        Sub_menu_criar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_criar_clienteActionPerformed(evt);
            }
        });
        Tabela_clientes.add(Sub_menu_criar_cliente);

        Sub_menu_consultar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_edit.png"))); // NOI18N
        Sub_menu_consultar_cliente.setText("Consultar Clientes");
        Sub_menu_consultar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_consultar_clienteActionPerformed(evt);
            }
        });
        Tabela_clientes.add(Sub_menu_consultar_cliente);

        Menu_tabelas.add(Tabela_clientes);

        Tabela_tarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/brick.png"))); // NOI18N
        Tabela_tarefas.setText("Tarefas");

        Sub_menu_criar_tarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/brick_add.png"))); // NOI18N
        Sub_menu_criar_tarefa.setText("Criar Tarefa");
        Sub_menu_criar_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_criar_tarefaActionPerformed(evt);
            }
        });
        Tabela_tarefas.add(Sub_menu_criar_tarefa);

        Sub_menu_consultar_tarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/brick_edit.png"))); // NOI18N
        Sub_menu_consultar_tarefas.setText("Consultar Tarefas");
        Sub_menu_consultar_tarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_consultar_tarefasActionPerformed(evt);
            }
        });
        Tabela_tarefas.add(Sub_menu_consultar_tarefas);

        Menu_tabelas.add(Tabela_tarefas);

        Barra_de_menu.add(Menu_tabelas);

        Menu_tarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bricks.png"))); // NOI18N
        Menu_tarefas.setText("Tarefas");
        Menu_tarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Sub_menu_atribuir_tarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/brick_link.png"))); // NOI18N
        Sub_menu_atribuir_tarefa.setText("Atribuir Tarefa");
        Sub_menu_atribuir_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_atribuir_tarefaActionPerformed(evt);
            }
        });
        Menu_tarefas.add(Sub_menu_atribuir_tarefa);

        Sub_menu_concluir_tarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/brick_go.png"))); // NOI18N
        Sub_menu_concluir_tarefa.setText("Concluir Tarefa");
        Sub_menu_concluir_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_concluir_tarefaActionPerformed(evt);
            }
        });
        Menu_tarefas.add(Sub_menu_concluir_tarefa);

        Barra_de_menu.add(Menu_tarefas);

        Menu_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report.png"))); // NOI18N
        Menu_relatorios.setText("Relatórios");
        Menu_relatorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Sub_menu_relatorio_tarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_go.png"))); // NOI18N
        Sub_menu_relatorio_tarefas.setText("Relatórios de Tarefas");
        Menu_relatorios.add(Sub_menu_relatorio_tarefas);

        Barra_de_menu.add(Menu_relatorios);

        Menu_sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/information.png"))); // NOI18N
        Menu_sobre.setText("Sobre");
        Menu_sobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Sub_menu_ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        Sub_menu_ajuda.setText("Ajuda");
        Sub_menu_ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_ajudaActionPerformed(evt);
            }
        });
        Menu_sobre.add(Sub_menu_ajuda);

        Sub_menu_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/information.png"))); // NOI18N
        Sub_menu_acerca.setText("Acerca");
        Sub_menu_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_menu_acercaActionPerformed(evt);
            }
        });
        Menu_sobre.add(Sub_menu_acerca);

        Barra_de_menu.add(Menu_sobre);

        setJMenuBar(Barra_de_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Area_de_trabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Area_de_trabalho)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sub_menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_sub_menu_logoutActionPerformed

    private void Sub_menu_ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_ajudaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Sub_menu_ajudaActionPerformed

    private void Sub_menu_criar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_criar_userActionPerformed
        // TODO add your handling code here:
        Tela_cadastro_usuario telacaduser = new Tela_cadastro_usuario();
        Area_de_trabalho.add(telacaduser);
        telacaduser.setVisible(true);
        
        
    }//GEN-LAST:event_Sub_menu_criar_userActionPerformed

    private void Sub_menu_consultar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_consultar_userActionPerformed
        // TODO add your handling code here: 
        Tela_consulta_usuario Tela_consulta_usuario = new Tela_consulta_usuario();
        Area_de_trabalho.add(Tela_consulta_usuario);
        Tela_consulta_usuario.setVisible(true);
    }//GEN-LAST:event_Sub_menu_consultar_userActionPerformed

    private void Sub_menu_criar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_criar_clienteActionPerformed
        // TODO add your handling code here:
        Tela_cadastro_clientes TelaCadCliente = new Tela_cadastro_clientes();
        Area_de_trabalho.add(TelaCadCliente);
        TelaCadCliente.setVisible(true);
    }//GEN-LAST:event_Sub_menu_criar_clienteActionPerformed

    private void Sub_menu_consultar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_consultar_clienteActionPerformed
        // TODO add your handling code here:?
        Tela_consulta_cliente TelaconsulCliente = new Tela_consulta_cliente();
        Area_de_trabalho.add(TelaconsulCliente);
        TelaconsulCliente.setVisible(true);
    }//GEN-LAST:event_Sub_menu_consultar_clienteActionPerformed

    private void Sub_menu_criar_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_criar_tarefaActionPerformed
        // TODO add your handling code here:
        Tela_cadastro_tarefas TelaCadTarefa = new Tela_cadastro_tarefas();
        Area_de_trabalho.add(TelaCadTarefa);
        TelaCadTarefa.setVisible(true);
    }//GEN-LAST:event_Sub_menu_criar_tarefaActionPerformed

    private void Sub_menu_consultar_tarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_consultar_tarefasActionPerformed
        // TODO add your handling code here:.
        Tela_consulta_tarefas TelaConsulTarefa = new Tela_consulta_tarefas();
        Area_de_trabalho.add(TelaConsulTarefa);
        TelaConsulTarefa.setVisible(true);
    }//GEN-LAST:event_Sub_menu_consultar_tarefasActionPerformed

    private void Sub_menu_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_acercaActionPerformed
        // TODO add your handling code here:
        Tela_Acerca TelaAcerca = new Tela_Acerca();
        Area_de_trabalho.add(TelaAcerca);
        TelaAcerca.setVisible(true);
    }//GEN-LAST:event_Sub_menu_acercaActionPerformed

    private void Sub_menu_atribuir_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_atribuir_tarefaActionPerformed
        // TODO add your handling code here:
        Tela_atribuicao_tarefa Telaatribuir = new Tela_atribuicao_tarefa();
        Area_de_trabalho.add(Telaatribuir);
        Telaatribuir.setVisible(true);
    }//GEN-LAST:event_Sub_menu_atribuir_tarefaActionPerformed

    private void Sub_menu_concluir_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_menu_concluir_tarefaActionPerformed
        // TODO add your handling code here:
        Tela_concluir_tarefa Telaconcluir = new Tela_concluir_tarefa();
        Area_de_trabalho.add(Telaconcluir);
        Telaconcluir.setVisible(true);
    }//GEN-LAST:event_Sub_menu_concluir_tarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    public JDesktopPane getArea_de_trabalho() {
        return Area_de_trabalho;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Area_de_trabalho;
    private javax.swing.JMenuBar Barra_de_menu;
    private javax.swing.JMenu Menu_relatorios;
    private javax.swing.JMenu Menu_sistema;
    private javax.swing.JMenu Menu_sobre;
    private javax.swing.JMenu Menu_tabelas;
    private javax.swing.JMenu Menu_tarefas;
    private javax.swing.JMenuItem Sub_menu_acerca;
    private javax.swing.JMenuItem Sub_menu_ajuda;
    private javax.swing.JMenuItem Sub_menu_atribuir_tarefa;
    private javax.swing.JMenuItem Sub_menu_concluir_tarefa;
    private javax.swing.JMenuItem Sub_menu_consultar_cliente;
    private javax.swing.JMenuItem Sub_menu_consultar_tarefas;
    private javax.swing.JMenuItem Sub_menu_consultar_user;
    private javax.swing.JMenuItem Sub_menu_criar_cliente;
    private javax.swing.JMenuItem Sub_menu_criar_tarefa;
    private javax.swing.JMenuItem Sub_menu_criar_user;
    private javax.swing.JMenuItem Sub_menu_relatorio_tarefas;
    private javax.swing.JMenu Tabela_clientes;
    private javax.swing.JMenu Tabela_tarefas;
    private javax.swing.JMenu Tabela_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem sub_menu_logout;
    // End of variables declaration//GEN-END:variables

   
}
