/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.bean.Usuario;
import Model.dao.UsuarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Cravid Ekuikui
 */
public class Tela_consulta_usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_consulta_usuario
     */
    public Tela_consulta_usuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Tabela_user.getModel();
        Tabela_user.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_user.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.consultaUsuario()) {
            modelo.addRow(new Object[]{
                u.getCodUser(),
                u.getNomeUser(),
                u.getEmailUser(),
                u.getNiveUser()
            });
        }

    }
    public void readJTable_forDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_user.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.consultaUsuario_por_descricao(desc)) {
            modelo.addRow(new Object[]{
                u.getCodUser(),
                u.getNomeUser(),
                u.getEmailUser(),
                u.getNiveUser()
            });
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Painel_de_consulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_user = new javax.swing.JTable();
        Botao_busca_user = new javax.swing.JButton();
        Campo_busca_user = new javax.swing.JTextField();
        Botao_editar_user = new javax.swing.JButton();
        Botao_apagar_user = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setMaximizable(true);
        setTitle("Consulta de Usuário");
        setName("Consulta de Usuário"); // NOI18N

        Painel_de_consulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tabela_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tabela_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Usuário", "Nome de Usuário", "Contacto", "Nível"
            }
        ));
        jScrollPane1.setViewportView(Tabela_user);

        Botao_busca_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_busca_user.setText("Procurar");
        Botao_busca_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_busca_userActionPerformed(evt);
            }
        });

        Campo_busca_user.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Campo_busca_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_busca_userActionPerformed(evt);
            }
        });

        Botao_editar_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_editar_user.setText("Editar");
        Botao_editar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_editar_userActionPerformed(evt);
            }
        });

        Botao_apagar_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_apagar_user.setText("Apagar");
        Botao_apagar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_apagar_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_de_consultaLayout = new javax.swing.GroupLayout(Painel_de_consulta);
        Painel_de_consulta.setLayout(Painel_de_consultaLayout);
        Painel_de_consultaLayout.setHorizontalGroup(
            Painel_de_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_de_consultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_de_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_de_consultaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_de_consultaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Painel_de_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_de_consultaLayout.createSequentialGroup()
                                .addComponent(Botao_busca_user)
                                .addGap(18, 18, 18)
                                .addComponent(Campo_busca_user, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_de_consultaLayout.createSequentialGroup()
                                .addComponent(Botao_editar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Botao_apagar_user)
                                .addGap(32, 32, 32))))))
        );
        Painel_de_consultaLayout.setVerticalGroup(
            Painel_de_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_de_consultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_de_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_busca_user)
                    .addComponent(Campo_busca_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_de_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_editar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_apagar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_de_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_de_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Campo_busca_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_busca_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_busca_userActionPerformed

    private void Botao_editar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_editar_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_editar_userActionPerformed

    private void Botao_apagar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_apagar_userActionPerformed
        // TODO add your handling code here:
        if(Tabela_user.getSelectedRow() != -1){
         
            Usuario user = new Usuario();
            UsuarioDAO userDAO = new UsuarioDAO();
            
            user.setCodUser((int) Tabela_user.getValueAt(Tabela_user.getSelectedRow(), 0));
            userDAO.Excluir(user);
            
            readJTable();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_Botao_apagar_userActionPerformed

    private void Botao_busca_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_busca_userActionPerformed
        // TODO add your handling code here:
        readJTable_forDesc(Campo_busca_user.getText());
    }//GEN-LAST:event_Botao_busca_userActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_apagar_user;
    private javax.swing.JButton Botao_busca_user;
    private javax.swing.JButton Botao_editar_user;
    private javax.swing.JTextField Campo_busca_user;
    private javax.swing.JPanel Painel_de_consulta;
    private javax.swing.JTable Tabela_user;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
