/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.bean.Clientes;
import Model.bean.Tarefa;
import Model.bean.Usuario;
import Model.dao.ClientesDAO;
import Model.dao.TarefaDAO;
import Model.dao.UsuarioDAO;

/**
 *
 * @author Cravid Ekuikui
 */
public class Tela_cadastro_tarefas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_cadastro_tarefas
     */
    public Tela_cadastro_tarefas() {
        initComponents();
        UsuarioDAO user = new UsuarioDAO();
        ClientesDAO cli = new ClientesDAO();

        for (Usuario u : user.consultaUsuario()) {
            nomeuser.addItem(u);
        }
        for (Clientes c : cli.consultaClientes()) {
            nomecliente.addItem(c);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_cadastro_tarefas = new javax.swing.JPanel();
        Label_descricao = new javax.swing.JLabel();
        Label_datafinal = new javax.swing.JLabel();
        Label_cliente = new javax.swing.JLabel();
        Label_tecnico = new javax.swing.JLabel();
        Label_observacoes = new javax.swing.JLabel();
        Label_datainicio = new javax.swing.JLabel();
        Label_estado = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        datainicial = new javax.swing.JFormattedTextField();
        datafinal = new javax.swing.JFormattedTextField();
        nomecliente = new javax.swing.JComboBox<>();
        nomeuser = new javax.swing.JComboBox<>();
        estado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacoes = new javax.swing.JTextArea();
        Botao_salvar_tarefa = new javax.swing.JButton();
        Botao_cancelar_tarefa = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Tarefas");

        Painel_cadastro_tarefas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Label_descricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_descricao.setText("Descrição da Tarefa");

        Label_datafinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_datafinal.setText("Data Final de Execução");

        Label_cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_cliente.setText("Cliente");

        Label_tecnico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_tecnico.setText("Técnico");

        Label_observacoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_observacoes.setText("Observções");

        Label_datainicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_datainicio.setText("Data Inicia de Execuçáol");

        Label_estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_estado.setText("Estado");

        descricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        datainicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        datainicial.setText("Ano-Mês-Dia");
        datainicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datainicialActionPerformed(evt);
            }
        });

        datafinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        datafinal.setText("Ano-Mês.Dia");

        nomecliente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nomecliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        nomeuser.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nomeuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        estado.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberto", "Pendente", "Cancelado", "Concluído" }));

        observacoes.setColumns(20);
        observacoes.setRows(5);
        jScrollPane1.setViewportView(observacoes);

        Botao_salvar_tarefa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_salvar_tarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        Botao_salvar_tarefa.setText("Salvar");
        Botao_salvar_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_salvar_tarefaActionPerformed(evt);
            }
        });

        Botao_cancelar_tarefa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_cancelar_tarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        Botao_cancelar_tarefa.setText("Cancelar");
        Botao_cancelar_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_cancelar_tarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_cadastro_tarefasLayout = new javax.swing.GroupLayout(Painel_cadastro_tarefas);
        Painel_cadastro_tarefas.setLayout(Painel_cadastro_tarefasLayout);
        Painel_cadastro_tarefasLayout.setHorizontalGroup(
            Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_descricao)
                            .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_cadastro_tarefasLayout.createSequentialGroup()
                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Label_datainicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(datainicial))
                                        .addGap(44, 44, 44)
                                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_datafinal)
                                            .addComponent(datafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_observacoes))
                                .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_estado))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_cliente)
                                            .addComponent(nomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Label_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(121, 121, 121))
                                            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(nomeuser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Botao_salvar_tarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Botao_cancelar_tarefa)))
                        .addGap(47, 47, 47))))
        );
        Painel_cadastro_tarefasLayout.setVerticalGroup(
            Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Label_descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_datainicio)
                    .addComponent(Label_datafinal)
                    .addComponent(Label_cliente)
                    .addComponent(Label_tecnico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_cadastro_tarefasLayout.createSequentialGroup()
                        .addComponent(Label_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                        .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Painel_cadastro_tarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Botao_salvar_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Botao_cancelar_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_cadastro_tarefasLayout.createSequentialGroup()
                                .addComponent(Label_observacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_cadastro_tarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_cadastro_tarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datainicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datainicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datainicialActionPerformed

    private void Botao_salvar_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_salvar_tarefaActionPerformed
        // TODO add your handling code here:
        Tarefa Task = new Tarefa();
        TarefaDAO Task_dao = new TarefaDAO();
        Clientes cli = (Clientes) nomecliente.getSelectedItem();
        int C = cli.getCodCliente();
        Usuario user = (Usuario) nomeuser.getSelectedItem();
        int U = user.getCodUser();
        String E = (String) estado.getSelectedItem();

        Task.setDescricao(descricao.getText());
        Task.setDataInicial(datainicial.getText());
        Task.setDataFinal(datafinal.getText());
        Task.setCliente(C);
        Task.setUsuario(U);
        Task.setEstado(E);
        Task.setObservacoes(observacoes.getText());

        Task_dao.criarTarefa(Task);

        descricao.setText("");
        observacoes.setText("");


    }//GEN-LAST:event_Botao_salvar_tarefaActionPerformed

    private void Botao_cancelar_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_cancelar_tarefaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Botao_cancelar_tarefaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_cancelar_tarefa;
    private javax.swing.JButton Botao_salvar_tarefa;
    private javax.swing.JLabel Label_cliente;
    private javax.swing.JLabel Label_datafinal;
    private javax.swing.JLabel Label_datainicio;
    private javax.swing.JLabel Label_descricao;
    private javax.swing.JLabel Label_estado;
    private javax.swing.JLabel Label_observacoes;
    private javax.swing.JLabel Label_tecnico;
    private javax.swing.JPanel Painel_cadastro_tarefas;
    private javax.swing.JFormattedTextField datafinal;
    private javax.swing.JFormattedTextField datainicial;
    private javax.swing.JTextField descricao;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Object> nomecliente;
    private javax.swing.JComboBox<Object> nomeuser;
    private javax.swing.JTextArea observacoes;
    // End of variables declaration//GEN-END:variables
}
