/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Cravid Ekuikui
 */
public class Tela_consulta_cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_consulta_cliente
     */
    public Tela_consulta_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_consulta_cliente = new javax.swing.JPanel();
        Botao_procurar_cliente = new javax.swing.JButton();
        Campo_busca_cliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_clientes = new javax.swing.JTable();
        Botao_editar_cliente = new javax.swing.JButton();
        Botao_apagar_cliente = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Consulta de Clientes");

        Painel_consulta_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Botao_procurar_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_procurar_cliente.setText("Procurar");

        Campo_busca_cliente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        Tabela_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Cliente", "NIF", "Telefone", "Casa Nº", "Rua", "Bairro", "Município"
            }
        ));
        jScrollPane1.setViewportView(Tabela_clientes);

        Botao_editar_cliente.setText("Editar");

        Botao_apagar_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_apagar_cliente.setText("Apagar");

        javax.swing.GroupLayout Painel_consulta_clienteLayout = new javax.swing.GroupLayout(Painel_consulta_cliente);
        Painel_consulta_cliente.setLayout(Painel_consulta_clienteLayout);
        Painel_consulta_clienteLayout.setHorizontalGroup(
            Painel_consulta_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_consulta_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_consulta_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_consulta_clienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Painel_consulta_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_consulta_clienteLayout.createSequentialGroup()
                                .addComponent(Botao_procurar_cliente)
                                .addGap(18, 18, 18)
                                .addComponent(Campo_busca_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_consulta_clienteLayout.createSequentialGroup()
                                .addComponent(Botao_editar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Botao_apagar_cliente)
                                .addGap(43, 43, 43))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_consulta_clienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        Painel_consulta_clienteLayout.setVerticalGroup(
            Painel_consulta_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_consulta_clienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Painel_consulta_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_procurar_cliente)
                    .addComponent(Campo_busca_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(Painel_consulta_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_editar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_apagar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_consulta_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_consulta_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_apagar_cliente;
    private javax.swing.JButton Botao_editar_cliente;
    private javax.swing.JButton Botao_procurar_cliente;
    private javax.swing.JTextField Campo_busca_cliente;
    private javax.swing.JPanel Painel_consulta_cliente;
    private javax.swing.JTable Tabela_clientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
