/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.bean.Usuario;
import Model.dao.UsuarioDAO;

/**
 *
 * @author Cravid Ekuikui
 */
public class Tela_cadastro_usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_cadastro_usuario
     */
    public Tela_cadastro_usuario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_cadastro_user = new javax.swing.JPanel();
        Label_nome_user = new javax.swing.JLabel();
        Label_senha_user = new javax.swing.JLabel();
        Label_email_user = new javax.swing.JLabel();
        Label_nivel_user = new javax.swing.JLabel();
        Botao_salvar_user = new javax.swing.JButton();
        Botao_cancelar_user = new javax.swing.JButton();
        nomeuser = new javax.swing.JTextField();
        senhauser = new javax.swing.JPasswordField();
        emailuser = new javax.swing.JTextField();
        niveluser = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de Usuário");
        setAutoscrolls(true);
        setName(""); // NOI18N

        Painel_cadastro_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Label_nome_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_nome_user.setText("Nome do Usuário");

        Label_senha_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_senha_user.setText("Senha");

        Label_email_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_email_user.setText("Email");

        Label_nivel_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_nivel_user.setText("Nível");

        Botao_salvar_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_salvar_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        Botao_salvar_user.setText("Salvar");
        Botao_salvar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_salvar_userActionPerformed(evt);
            }
        });

        Botao_cancelar_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_cancelar_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        Botao_cancelar_user.setText("Cancelar");
        Botao_cancelar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_cancelar_userActionPerformed(evt);
            }
        });

        nomeuser.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nomeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeuserActionPerformed(evt);
            }
        });

        senhauser.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        emailuser.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        niveluser.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        niveluser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Nível...", " ", "Administrador", "Secretária", "Técnico" }));

        javax.swing.GroupLayout Painel_cadastro_userLayout = new javax.swing.GroupLayout(Painel_cadastro_user);
        Painel_cadastro_user.setLayout(Painel_cadastro_userLayout);
        Painel_cadastro_userLayout.setHorizontalGroup(
            Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_cadastro_userLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_cadastro_userLayout.createSequentialGroup()
                        .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_nome_user, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Painel_cadastro_userLayout.createSequentialGroup()
                                .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(senhauser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_email_user)
                                    .addComponent(Label_senha_user, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailuser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(niveluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_nivel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(Painel_cadastro_userLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Botao_salvar_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Botao_cancelar_user)
                        .addGap(37, 37, 37))))
        );
        Painel_cadastro_userLayout.setVerticalGroup(
            Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_cadastro_userLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Label_nome_user, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_senha_user)
                    .addComponent(Label_nivel_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhauser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Label_email_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(Painel_cadastro_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_cancelar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_salvar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_cadastro_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_cadastro_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_cancelar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_cancelar_userActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Botao_cancelar_userActionPerformed

    private void Botao_salvar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_salvar_userActionPerformed
        // TODO add your handling code here:
        Usuario user = new Usuario();
        UsuarioDAO user_dao = new UsuarioDAO();
        String b = (String) niveluser.getSelectedItem();

        user.setNomeUser(nomeuser.getText());
        user.setSenhaUser(senhauser.getText());
        user.setEmailUser(emailuser.getText());
        user.setNiveUser(b);

        user_dao.criarUsuario(user);

        nomeuser.setText("");
        senhauser.setText("");
        emailuser.setText("");

    }//GEN-LAST:event_Botao_salvar_userActionPerformed

    private void nomeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_cancelar_user;
    private javax.swing.JButton Botao_salvar_user;
    private javax.swing.JLabel Label_email_user;
    private javax.swing.JLabel Label_nivel_user;
    private javax.swing.JLabel Label_nome_user;
    private javax.swing.JLabel Label_senha_user;
    private javax.swing.JPanel Painel_cadastro_user;
    private javax.swing.JTextField emailuser;
    private javax.swing.JComboBox<String> niveluser;
    private javax.swing.JTextField nomeuser;
    private javax.swing.JPasswordField senhauser;
    // End of variables declaration//GEN-END:variables
}
