/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.bean.Tarefa;
import Model.bean.Usuario;
import Model.dao.TarefaDAO;
import Model.dao.UsuarioDAO;

/**
 *
 * @author Cravid Ekuikui
 */
public class Tela_atribuicao_tarefa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_atribuicao_tarefa
     */
    public Tela_atribuicao_tarefa() {
        initComponents();
        UsuarioDAO user = new UsuarioDAO();
        TarefaDAO task = new TarefaDAO();

        for (Usuario u : user.consultaUsuario()) {
            nomeusuario.addItem(u);
           
        }
        for (Tarefa t : task.consultaTarefas_nao_atribuidas()) {
            descricao.addItem(t);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Painel_atribuicao = new javax.swing.JPanel();
        Label_seleciona_tarefa = new javax.swing.JLabel();
        Label_selecione_tecnico = new javax.swing.JLabel();
        Label_indique_data = new javax.swing.JLabel();
        descricao = new javax.swing.JComboBox<>();
        nomeusuario = new javax.swing.JComboBox<>();
        datafinal = new javax.swing.JFormattedTextField();
        Botao_atribuir = new javax.swing.JButton();
        Botao_cancelar_atribuicao = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setTitle("Atribuição de Tarefas");
        setAutoscrolls(true);

        Painel_atribuicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Painel_atribuicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Painel_atribuicaoKeyTyped(evt);
            }
        });

        Label_seleciona_tarefa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_seleciona_tarefa.setText("Selecione a Tarefa");

        Label_selecione_tecnico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_selecione_tecnico.setText("Selecione o técnico");

        Label_indique_data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_indique_data.setText("Indique a data para o término");

        descricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descricao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        nomeusuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nomeusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        datafinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        datafinal.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        Botao_atribuir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_atribuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        Botao_atribuir.setText("Atribuir");
        Botao_atribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_atribuirActionPerformed(evt);
            }
        });

        Botao_cancelar_atribuicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botao_cancelar_atribuicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        Botao_cancelar_atribuicao.setText("Cancelar");
        Botao_cancelar_atribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_cancelar_atribuicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_atribuicaoLayout = new javax.swing.GroupLayout(Painel_atribuicao);
        Painel_atribuicao.setLayout(Painel_atribuicaoLayout);
        Painel_atribuicaoLayout.setHorizontalGroup(
            Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_atribuicaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_atribuicaoLayout.createSequentialGroup()
                        .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Painel_atribuicaoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Botao_atribuir))
                            .addGroup(Painel_atribuicaoLayout.createSequentialGroup()
                                .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                                .addComponent(datafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Botao_cancelar_atribuicao)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_atribuicaoLayout.createSequentialGroup()
                        .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descricao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_atribuicaoLayout.createSequentialGroup()
                                .addComponent(Label_selecione_tecnico)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))
                    .addGroup(Painel_atribuicaoLayout.createSequentialGroup()
                        .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_seleciona_tarefa)
                            .addGroup(Painel_atribuicaoLayout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(Label_indique_data)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Painel_atribuicaoLayout.setVerticalGroup(
            Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_atribuicaoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Label_seleciona_tarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_selecione_tecnico)
                    .addComponent(Label_indique_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(Painel_atribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_atribuir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_cancelar_atribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_atribuicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_atribuicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Painel_atribuicaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Painel_atribuicaoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Painel_atribuicaoKeyTyped

    private void Botao_atribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_atribuirActionPerformed
        // TODO add your handling code here:
        Tarefa Task = new Tarefa();
        TarefaDAO Task_dao = new TarefaDAO();

        Tarefa cbtask = (Tarefa) descricao.getSelectedItem();
        int codtarefa = cbtask.getCodTarefa();
        Usuario user = (Usuario) nomeusuario.getSelectedItem();
        int U = user.getCodUser();

        Task.setDataFinal(datafinal.getText());
        Task.setUsuario(U);
        Task.setCodTarefa(codtarefa);

        Task_dao.AtribuirTarefa(Task);

        descricao.setSelectedIndex(0);
        nomeusuario.setSelectedIndex(0);
        datafinal.setText("");


    }//GEN-LAST:event_Botao_atribuirActionPerformed

    private void Botao_cancelar_atribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_cancelar_atribuicaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Botao_cancelar_atribuicaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_atribuir;
    private javax.swing.JButton Botao_cancelar_atribuicao;
    private javax.swing.JLabel Label_indique_data;
    private javax.swing.JLabel Label_seleciona_tarefa;
    private javax.swing.JLabel Label_selecione_tecnico;
    private javax.swing.JPanel Painel_atribuicao;
    private javax.swing.JFormattedTextField datafinal;
    private javax.swing.JComboBox<Object> descricao;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Object> nomeusuario;
    // End of variables declaration//GEN-END:variables
}
